[package]
name = "pixels-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.1", features = ["derive"] }
wgpu = "0.19.1"
winit = { version = "0.30.0", features = ["rwh_05"] }

[dev-dependencies]
test-case = "3.3.1"